version: "3"
services:
  backend:
    build: ./backend
    container_name: backend_container
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=development
      - DATABASE=mongodb://mongo:27017/aquaVision
      - PORT=8888
      - NODE_OPTIONS=--openssl-legacy-provider
      - JWT_SECRET=secret_key_1234

    command: sh -c "npm run dev"

    networks:
      - server-mongo

    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend_container
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:8888/api
      - NODE_OPTIONS=--openssl-legacy-provider

    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo_container
    volumes:
      - mongodb_data:/data/db
    networks:
      - server-mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"

volumes:
  mongodb_data:

networks:
  server-mongo:
